---
hocs-generic-service:
  nameOverride: hocs-search

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-search
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=70
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
        -Dhttps.proxyHost=hocs-outbound-proxy.{{ .Release.Namespace }}.svc.cluster.local
        -Dhttps.proxyPort=31290
        -Dhttp.nonProxyHosts=*.{{ .Release.Namespace }}.svc.cluster.local
      springProfiles: 'aws'
      elasticPrefix: '{{ .Release.Namespace }}-latest'
      elasticMode: 'SINGULAR'
      searchQueueName: '{{ .Release.Namespace }}-search-sqs'
