---
kind: pipeline
type: kubernetes
name: deploy tag
trigger:
  event:
    - tag
  branch:
    - main

steps:
  - name: checkout
    image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:1.1.1
    commands:
      - git fetch --tags
      - git checkout ${DRONE_TAG}
      - git submodule update --init --recursive

  - &deploy
    name: cs-dev
    image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:1.1.1
    environment:
      CHART_NAME: hocs-search-multiple
      CHART_VERSION: ^1.0.0
      KUBE_CLUSTER: acp-notprod
      KUBE_NAMESPACE: cs-dev
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      KUBE_TOKEN:
        from_secret: cs_notprod
      VERSION: ${DRONE_TAG}
    commands:
      - ./ci/helm/helm-chart-deploy.sh --values ./helm/hocs-search.yaml
    depends_on:
      - checkout

  - <<: *deploy
    name: wcs-dev
    environment:
      KUBE_NAMESPACE: wcs-dev
    commands:
      - commands:
          - ./ci/helm/helm-chart-deploy.sh --values ./helm/hocs-search.yaml --values ./helm/wcs/hocs-search.yaml
    depends_on:
      - cs-dev

  - &deploy-consumer
    name: cs-dev-consumer
    image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:1.1.1
    environment:
      CHART_NAME: hocs-search-multiple-consumer
      CHART_VERSION: ^1.0.0
      KUBE_CLUSTER: acp-notprod
      KUBE_NAMESPACE: cs-dev
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      KUBE_TOKEN:
        from_secret: cs_notprod
      VERSION: ${DRONE_TAG}
    commands:
      - ./ci/helm/helm-chart-deploy.sh --values ./helm/hocs-search-consumer.yaml
    depends_on:
      - checkout

  - <<: *deploy-consumer
    name: wcs-dev-consumer
    environment:
      KUBE_NAMESPACE: wcs-dev
    commands:
      - ./ci/helm/helm-chart-deploy.sh --values ./helm/hocs-search-consumer.yaml --values ./helm/wcs/hocs-search-consumer.yaml
    depends_on:
      - cs-dev-consumer
