version: '3.9'

services:

  localstack:
    image: localstack/localstack:0.11.1
    ports:
      - "4566:4566"
      - "4571:4571"
      - "4578:4578"
    networks:
      - hocs-network
    environment:
      HOSTNAME_EXTERNAL: localstack
      DEFAULT_REGION: eu-west-2
      SERVICES: es, sqs
      ELASTIC_MAPPING_PATH: "@/docker-entrypoint-initaws.d/elastic_mapping.json"
    volumes:
      - ./config/localstack:/docker-entrypoint-initaws.d

networks:
  hocs-network:
