management:
health:
  elasticsearch:
    enabled: false

aws:
  region: eu-west-2
  sqs:
    search:
      access-key: test
      secret-key: test
      name: search-queue
      url: http://${localstack.host:localhost}:4566/000000000000/${aws.sqs.search.name}
  es:
    host: localhost.localstack.cloud
    port: 4566
    results-limit: 500
    index-prefix: local
