package uk.gov.digital.ho.hocs.search.application;

public enum LogEvent {
    REST_HELPER_NOT_FOUND,
    REST_HELPER_INTERNAL_SERVER_ERROR,
    REST_HELPER_MALFORMED_RESPONSE,
    INFO_CLIENT_GET_TOPIC_SUCCESS,
    INFO_CLIENT_GET_TOPIC_FAILURE,
    INFO_CLIENT_GET_ALL_TOPIC_UUID_SUCCESS,
    INFO_CLIENT_GET_ALL_TOPIC_UUID_FAILURE,
    CASE_UPDATE_FAILED,
    CASE_SAVE_FAILED,
    CASE_NOT_FOUND,
    CACHE_PRIME_FAILED;
    public static final String EVENT = "event_id";
}
