package uk.gov.digital.ho.hocs.search.application.queue;

public enum EventType {
    CASE_CREATED,
    CASE_UPDATED,
    CASE_DELETED,
    CASE_COMPLETED,
    CORRESPONDENT_CREATED,
    CORRESPONDENT_DELETED,
    CORRESPONDENT_UPDATED,
    CASE_TOPIC_CREATED,
    CASE_TOPIC_DELETED,
    SOMU_ITEM_CREATED,
    SOMU_ITEM_UPDATED,
    SOMU_ITEM_DELETED
}
