---
hocs-generic-service:
  deployment:
    annotations:
      downscaler/downtime: "Sat-Sun 00:00-24:00 Europe/London,Mon-Fri 00:00-07:55 Europe/London,Mon-Fri 18:05-24:00 Europe/London"

  app:
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 512Mi
    env:
      elasticPrefix: 'cs-dev-202303221400'
