name: 'Task Branch pipeline'
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  push:
    tags:  [ * ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Quay.io Container Registry
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USER_NAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: quay.io/ukhomeofficedigital/hocs-search
          tags: |
            type=raw,value=${{ github.event.pull_request.head.sha }}
            type=semver,pattern={{version}}
