name: 'Task Branch Pipeline'
on:
  push:
    tags: [ '[0-9]+.[0-9].[0-9]' ]
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USER_NAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Calculate Container Tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: quay.io/ukhomeofficedigital/hocs-search
          tags: |
            type=raw,value=${{ github.event.pull_request.head.sha }}
            type=semver,pattern={{version}}
      - name: Build Container
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
